#!/bin/bash

git log --pretty=format:"%x09%s" origin/master..HEAD | grep 'fixup' > /dev/null
fixupFound="$?"
if [ $fixupFound -eq 0 ]; then
    echo "There are fixup commits, please autosquash them first." 
    exit 1
else
    exit 0
fi
